apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cms-qa
spec:
  template:
    spec:
      containers:
      - image: cms
      env:
      - name: APP_KEYS
        valueFrom:
          secretKeyRef:
            key: latest
            name: strapi-app-keys
      - name: API_TOKEN_SALT
        valueFrom:
          secretKeyRef:
            key: latest
            name: strapi-api-token-salt
