steps:
- name: 'ubuntu'
  script: |
    #!/usr/bin/env bash
    set -e
    set -x

    ./generate-config.sh cms /workspace/config/cms
    ./generate-config.sh frontend /workspace/config/frontend
  env:
  - DOMAIN_NAME=$_DOMAIN_NAME
  - SKAFFOLD_NAMESPACE=$_SKAFFOLD_NAMESPACE
  - CMS_SERVICE_ACCT=$_CMS_SERVICE_ACCT
  - REGION=$_REGION
  - INSTANCE_NAME=$_INSTANCE_NAME
  - PROJECT_ID=$PROJECT_ID

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
    - gcloud
    - container
    - clusters
    - get-credentials
    - ${_CLUSTER_NAME}
    - --region
    - ${_REGION}
  id: get-cluster-credentials
  waitFor: ['-']

- name: gcr.io/cloud-builders/kubectl
  script: |
    #!/usr/bin/env bash
    kubectl delete ns $SKAFFOLD_NAMESPACE --ignore-not-found=true --wait=false &
    kubectl wait namespace/$SKAFFOLD_NAMESPACE --for=delete --timeout=-1s
    kubectl create ns $SKAFFOLD_NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
    kubectl annotate ns $SKAFFOLD_NAMESPACE cnrm.cloud.google.com/project-id=$PROJECT_ID --overwrite
    kubectl label ns $SKAFFOLD_NAMESPACE shared-gateway-access='true' --overwrite
  env:
  - SKAFFOLD_NAMESPACE=$_SKAFFOLD_NAMESPACE
  - PROJECT_ID=$PROJECT_ID
  id: create-namespace
  waitFor:
  - get-cluster-credentials

- name: gcr.io/k8s-skaffold/skaffold
  script: |
    #!/usr/bin/env bash
    skaffold build --file-output=tags.json --profile=qa --build-concurrency=0
  env:
  - SKAFFOLD_NAMESPACE=$_SKAFFOLD_NAMESPACE
  - SKAFFOLD_DEFAULT_REPO=$_SKAFFOLD_DEFAULT_REPO
  id: create-artifacts
  waitFor: ['-']

- name: gcr.io/k8s-skaffold/skaffold
  script: |
    #!/usr/bin/env bash
    cp /workspace/config/cms/.env.config cms/kubernetes-manifests/config/.env.config
    cp /workspace/config/cms/.env.secret cms/kubernetes-manifests/config/.env.secret
    cp /workspace/config/frontend/.env.config frontend/kubernetes-manifests/prod/.env.config
    cp /workspace/config/frontend/.env.secret frontend/kubernetes-manifests/prod/.env.secret
    skaffold deploy --build-artifacts=tags.json --profile=qa --status-check=false
  env:
  - SKAFFOLD_NAMESPACE=$_SKAFFOLD_NAMESPACE
  - SKAFFOLD_DEFAULT_REPO=$_SKAFFOLD_DEFAULT_REPO
  waitFor:
  - create-namespace
  - create-artifacts

substitutions:
  _SKAFFOLD_NAMESPACE: staging
  _REGION: europe-west1
  _CLUSTER_NAME: review-apps
  _CMS_SERVICE_ACCT: cms-sa
  _DOMAIN_NAME: microserve.dev
  _SKAFFOLD_DEFAULT_REPO: europe-west1-docker.pkg.dev/mgalite-ts24-playground/go-eat
  _INSTANCE_NAME: cms-instance

options:
  machineType: 'E2_HIGHCPU_8'
