apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: gke-review-apps-delivery-workshop
build:
  local:
    concurrency: 0
  artifacts:
    - image: cms
      context: cms
      docker:
        dockerfile: Dockerfile
    - image: frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
profiles:
  - name: dev
    manifests:
      kustomize:
        paths:
          - cms/kubernetes-manifests/dev
          - frontend/kubernetes-manifests/dev
    deploy:
      kubectl:
        hooks:
          after:
            - container:
                command:
                  - psql
                  - -c
                  - SELECT 'CREATE DATABASE cms' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'cms')
                  - -U
                  - postgres
                podName: postgres-*
      kubeContext: minikube
  - name: prod
    build:
      artifacts:
        - image: cms
          context: cms
          docker:
            dockerfile: Dockerfile.prod
        - image: frontend
          context: frontend
          docker:
            dockerfile: Dockerfile.prod
      local:
        push: true
    manifests:
      kustomize:
        paths:
          - cms/kubernetes-manifests/prod
          - frontend/kubernetes-manifests/prod
  - name: cb
    build:
      googleCloudBuild: {}
