apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: gke-review-apps-delivery-workshop
build:
  local:
    concurrency: 0
  artifacts:
    - image: cms
      context: cms
      docker:
        dockerfile: Dockerfile
    - image: frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
      - cms/kubernetes-manifests/dev
      - frontend/kubernetes-manifests/dev
profiles:
  - name: dev
    activation:
      - kubeContext: minikube
    deploy:
      kubectl:
        defaultNamespace: go-eat
        hooks:
          after:
            - container:
                command:
                  - psql
                  - -c
                  - SELECT 'CREATE DATABASE cms' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'cms')
                  - -U
                  - postgres
                podName: postgres-*
  - name: prod
    build:
      artifacts:
        - image: cms
          context: cms
          docker:
            dockerfile: Dockerfile.prod
        - image: frontend
          context: frontend
          docker:
            dockerfile: Dockerfile.prod
    manifests:
      kustomize:
        paths:
          - cms/kubernetes-manifests/prod
          - frontend/kubernetes-manifests/prod
    deploy:
      kubeContext: prod
      kubectl:
        defaultNamespace: go-eat
  - name: cb
    build:
      googleCloudBuild: {}
