apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-deployment
spec:
  selector:
    matchLabels:
      app: cms
  template:
    metadata:
      labels:
        app: cms
    spec:
      containers:
      - name: cms
        image: cms
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: '3000'
        - name: HOSTNAME
          value: localhost
