- op: add
  path: "/spec/template/spec/containers/-"
  value:
    name: cloud-sql-proxy
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0
    args:
      - "--structured-logs"
      - "--port=5432"
      - "--auto-iam-authn"
      - "INSTANCE_CONNECTION_NAME" # will be replaced by config.data.INSTANCE_CONNECTION_NAME
    securityContext:
      runAsNonRoot: true
    resources:
      requests:
        memory: "2Gi"
        cpu: "1"
      limits:
        memory: "2Gi"
        cpu: "1"
- op: replace
  path: "/spec/template/spec/containers/0/env/2/valueFrom"
  value:
    secretKeyRef:
      key: DATABASE_URL
      name: cms-secrets
- op: remove
  path: "/spec/template/spec/containers/0/env/2/value"
