- op: remove
  path: "/spec/template/spec/containers/0/env/2"
- op: add
  path: "/spec/template/spec/containers/0/env/-"
  value:
    name: DATABASE_HOST
    value: "set-by-operator"
- op: add
  path: "/spec/template/spec/containers/0/env/-"
  value:
    name: DATABASE_PORT
    value: "set-by-operator"
- op: add
  path: "/spec/template/spec/containers/0/env/-"
  value:
    name: DATABASE_USERNAME
    valueFrom:
      secretKeyRef:
        name: cms-secrets
        key: GCP_SQL_SERVICE_ACCOUNT
- op: add
  path: "/spec/template/spec/containers/0/env/-"
  value:
    name: DATABASE_NAME
    valueFrom:
      secretKeyRef:
        name: cms-secrets
        key: DATABASE_NAME
