apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- serviceaccount.yaml

patches:
- path: deployment.yaml
  target:
    kind: Deployment
    name: cms
- path: deployment.patch.yaml
  target:
    kind: Deployment
    name: cms

secretGenerator:
- name: cms-secrets
  envs:
  - .env.secret

configMapGenerator:
  - name: cms-config
    envs:
    - .env.config

replacements:
  - source:
      kind: ConfigMap
      name: cms-config
      fieldPath: data.INSTANCE_CONNECTION_NAME
    targets:
      - select:
          kind: Deployment
          name: cms
        fieldPaths:
          - spec.template.spec.containers.[name=cloud-sql-proxy].args.3
  - source:
      kind: ConfigMap
      name: cms-config
      fieldPath: data.GCP_SERVICE_ACCOUNT
    targets:
      - select:
          kind: ServiceAccount
          name: cms
        fieldPaths:
          - metadata.annotations.iam\.gke\.io/gcp-service-account
