apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- serviceaccount.yaml

patches:
- path: deployment.yaml
  target:
    kind: Deployment
    name: cms
- path: deployment.patch.yaml
  target:
    kind: Deployment
    name: cms

secretGenerator:
- name: cms-creds
  envs:
  - .cms.env.secret
