apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: frontend-qa
spec:
  template:
    spec:
      containers:
      - image: frontend
        ports:
          - name: http1
            containerPort: 3000
