apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../prod
- sqldatabase.yaml
- workloadidentity.yaml

replacements:
  - source:
      kind: ConfigMap
      name: cms-config
      fieldPath: data.INSTANCE_NAME
    targets:
      - select:
          kind: Database
          name: sqldatabase
        fieldPaths:
        - spec.forProvider.instance
  - source:
      kind: ConfigMap
      name: cms-config
      fieldPath: data.GCP_SERVICE_ACCOUNT
    targets:
      - select:
          kind: ServiceAccountIAMMember
          name: service-account-iam-member
        fieldPaths:
        - spec.forProvider.serviceAccountId
  - source:
      kind: ConfigMap
      name: cms-config
      fieldPath: data.WORKLOAD_IDENTITY_SERVICE_ACCOUNT
    targets:
      - select:
          kind: ServiceAccountIAMMember
          name: service-account-iam-member
        fieldPaths:
          - spec.forProvider.member
        options:
          delimiter: ':'
          index: 1
  - source:
      kind: ConfigMap
      name: cms-config
      fieldPath: data.DATABASE_NAME
    targets:
      - select:
          kind: SQLDatabase
          name: sqldatabase
