apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend
        resources:
          requests:
            memory: "500Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
          - name: PORT
            value: "3000"
          - name: HOSTNAME
            value: "0.0.0.0"
          - name: STRAPI_API_URL
            value: http://cms:1337/api
          - name: STRAPI_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: creds
                key: STRAPI_API_TOKEN
