apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cms-dev
spec:
  template:
    spec:
      containers:
      - image: cms
        ports:
          - name: http1
            containerPort: 1337
