apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- httproute.yaml

patches:
  - path: deployment.yaml

secretGenerator:
- name: creds
  envs:
  - .env.secret

configMapGenerator:
  - name: config
    envs:
    - .env.config

replacements:
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.HTTP_ROUTE_HOSTNAME
  targets:
    - select:
        kind: HTTPRoute
        name: frontend
      fieldPaths:
      - spec.hostnames.0
