name: Deploy
on:
  workflow_call:
    inputs:
      profile:
        type: string
        required: true
      namespace:
        type: string
        required: true
      runs-on:
        type: string
        required: true
      environment:
        type: string
        required: true
jobs:
  deploy:
    runs-on: ${{ inputs.runs-on }}
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ vars.WIF_PROVIDER }}'
          service_account: '${{ vars.WIF_SERVICE_ACCOUNT }}'

      - name: Generate Config
        run: |
          ./generate-config.sh cms
          ./generate-config.sh frontend
          echo SKAFFOLD_NAMESPACE=$SKAFFOLD_NAMESPACE >> skaffold.env
          echo SKAFFOLD_DEFAULT_REPO=${{ vars.AR_REPO }} >> skaffold.env
        env:
          DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
          CMS_SERVICE_ACCT: ${{ vars.CMS_SERVICE_ACCT }}
          REGION: ${{ vars.REGION }}
          INSTANCE_NAME: ${{ vars.INSTANCE_NAME }}
          PROJECT_ID: ${{ vars.PROJECT_ID }}
          SKAFFOLD_NAMESPACE: ${{ inputs.namespace }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v3'

      - name: Docker Auth
        run: gcloud auth configure-docker ${{ vars.REGION }}-docker.pkg.dev

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v3'
        with:
          project_id: ${{ vars.PROJECT_ID }}
          location: ${{ vars.REGION }}
          cluster_name: ${{ vars.CLUSTER_NAME }}
          namespace: ${{ inputs.namespace }}

      - name: Create Namespace
        run: |
          kubectl create ns $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
          kubectl annotate ns $NAMESPACE cnrm.cloud.google.com/project-id=$PROJECT_ID --overwrite
          kubectl label ns $NAMESPACE shared-gateway-access='true' --overwrite
        env:
          NAMESPACE: ${{ inputs.namespace }}
          PROJECT_ID: ${{ vars.PROJECT_ID }}

      - name: Setup Skaffold
        uses: heypigeonhq/setup-skaffold@v1.0.0

      - name: Deploy
        run: |
          skaffold run --profile=${{ inputs.profile }}
