name: Deploy-Manually

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        required: true
      profile:
        type: string
        required: true

jobs:
  call-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    uses: ./.github/workflows/deploy.yaml
    with:
      profile: ${{ inputs.profile }}
      workload_identity_provider: '${{ vars.WIF_PROVIDER }}'
      service_account: '${{ vars.WIF_SERVICE_ACCOUNT }}'
      domain_name: ${{ vars.DOMAIN_NAME }}
      cms_service_acct: ${{ vars.CMS_SERVICE_ACCT }}
      region: ${{ vars.REGION }}
      instance_name: ${{ vars.INSTANCE_NAME }}
      project_id: ${{ vars.PROJECT_ID }}
      ar_repo: ${{ vars.AR_REPO }}
      cluster_name: ${{ vars.CLUSTER_NAME }}
      namespace: pr-${{ github.event.number }}
      runs-on: ubuntu-latest
